test:
	gcc test.c -o output.out

fibonacci:
	gcc fibonacci.c -o output.out
	./output.out

fibonacci_modularized:
	gcc fibonacci_modularized.c -o output.out
	./output.out

max:
	gcc max.c -o output.out

max_modularized:
	gcc max_modularized.c -o output.out

input:
	cat ../data/test1.txt | ./output.out
	cat ../data/test2.txt | ./output.out
	cat ../data/test3.txt | ./output.out
