practice:
	gcc practice.c -o output.out

struct:
	gcc struct.c -o output.out
	./output.out

test:
	gcc test.c -o output.out

input:
	cat ../data/2d_1.txt | ./output.out
	cat ../data/2d_2.txt | ./output.out
	cat ../data/2d_3.txt | ./output.out
