maze:
	gcc maze.c -o output.out
	./output.out 10 10

maze_solve:
	gcc maze.c -o output.out
	./output.out 10 10 s

maze_answer:
	gcc maze_answer.c -o output.out
	./output.out 10 10

maze_answer_solve:
	gcc maze_answer.c -o output.out
	./output.out 10 10 s
