practice:
	gcc practice.c -o output.out

string:
	gcc string.c -o output.out
	./output.out

homework:
	gcc homework.c -o output.out

test:
	gcc test.c -o output.out

input:
	cat ../data/test_1.txt | ./output.out
	cat ../data/test_2.txt | ./output.out
	cat ../data/test_3.txt | ./output.out

string_input:
	cat ../data/string1.txt | ./output.out
	cat ../data/string2.txt | ./output.out
	cat ../data/string3.txt | ./output.out
