homework:
	gcc homework.c -o output.out

test:
	gcc test.c -o output.out

max:
	gcc max.c -o output.out

input:
	cat ../data/test1.txt | ./output.out
	cat ../data/test2.txt | ./output.out
	cat ../data/test3.txt | ./output.out

string_input:
	cat ../data/string1.txt | ./output.out
	cat ../data/string2.txt | ./output.out
	cat ../data/string3.txt | ./output.out
