practice:
	gcc practice.c -o output.out

average:
	gcc average.c -o output.out

test:
	gcc test.c -o output.out

input:
	cat ../data/test1.txt | ./output.out
	cat ../data/test2.txt | ./output.out
	cat ../data/test3.txt | ./output.out
